package com.likelion.giljobe.domain;

public enum ResidenceEnum {
    ALL, SEOUL, BUSAN, DAEGU, INCHEON, GWANGJU, DAEJEON, ULSAN,
    GYOUNGGI, GANGWON, CHUNGBUK, CHUNGNAM, JEONBUK, JEONNAM, GYEONGBUK, GYEONGNAM,
    JEJU, SEJONG
}